const arr = [
    {
        id: 290,
        screen_id: 3,
        row: 'A',
        number: 1,
    },
    {
        id: 291,
        screen_id: 3,
        row: 'A',
        number: 2,
    },
    {
        id: 292,
        screen_id: 3,
        row: 'A',
        number: 3,
    },
    {
        id: 293,
        screen_id: 3,
        row: 'A',
        number: 4,
    },
    {
        id: 294,
        screen_id: 3,
        row: 'A',
        number: 5,
    },
    {
        id: 295,
        screen_id: 3,
        row: 'A',
        number: 6,
    },
    {
        id: 296,
        screen_id: 3,
        row: 'A',
        number: 7,
    },
    {
        id: 297,
        screen_id: 3,
        row: 'A',
        number: 8,
    },
    {
        id: 298,
        screen_id: 3,
        row: 'A',
        number: 9,
    },
    {
        id: 302,
        screen_id: 3,
        row: 'B',
        number: 1,
    },
    {
        id: 303,
        screen_id: 3,
        row: 'B',
        number: 2,
    },
    {
        id: 304,
        screen_id: 3,
        row: 'B',
        number: 3,
    },
    {
        id: 305,
        screen_id: 3,
        row: 'B',
        number: 4,
    },
    {
        id: 306,
        screen_id: 3,
        row: 'B',
        number: 5,
    },
    {
        id: 307,
        screen_id: 3,
        row: 'B',
        number: 6,
    },
    {
        id: 308,
        screen_id: 3,
        row: 'B',
        number: 7,
    },
    {
        id: 309,
        screen_id: 3,
        row: 'B',
        number: 8,
    },
    {
        id: 310,
        screen_id: 3,
        row: 'B',
        number: 9,
    },
    {
        id: 311,
        screen_id: 3,
        row: 'B',
        number: 10,
    },
    {
        id: 312,
        screen_id: 3,
        row: 'C',
        number: 1,
    },
    {
        id: 313,
        screen_id: 3,
        row: 'C',
        number: 2,
    },
    {
        id: 314,
        screen_id: 3,
        row: 'C',
        number: 3,
    },
    {
        id: 315,
        screen_id: 3,
        row: 'C',
        number: 4,
    },
    {
        id: 316,
        screen_id: 3,
        row: 'C',
        number: 5,
    },
    {
        id: 317,
        screen_id: 3,
        row: 'C',
        number: 6,
    },
    {
        id: 318,
        screen_id: 3,
        row: 'C',
        number: 7,
    },
    {
        id: 319,
        screen_id: 3,
        row: 'C',
        number: 8,
    },
    {
        id: 320,
        screen_id: 3,
        row: 'C',
        number: 9,
    },
    {
        id: 321,
        screen_id: 3,
        row: 'C',
        number: 10,
    },
    {
        id: 322,
        screen_id: 3,
        row: 'D',
        number: 1,
    },
    {
        id: 323,
        screen_id: 3,
        row: 'D',
        number: 2,
    },
    {
        id: 324,
        screen_id: 3,
        row: 'D',
        number: 3,
    },
    {
        id: 325,
        screen_id: 3,
        row: 'D',
        number: 4,
    },
    {
        id: 326,
        screen_id: 3,
        row: 'D',
        number: 5,
    },
    {
        id: 327,
        screen_id: 3,
        row: 'D',
        number: 6,
    },
    {
        id: 328,
        screen_id: 3,
        row: 'D',
        number: 7,
    },
    {
        id: 329,
        screen_id: 3,
        row: 'D',
        number: 8,
    },
    {
        id: 330,
        screen_id: 3,
        row: 'D',
        number: 9,
    },
    {
        id: 331,
        screen_id: 3,
        row: 'D',
        number: 10,
    },
    {
        id: 332,
        screen_id: 3,
        row: 'D',
        number: 11,
    },
    {
        id: 333,
        screen_id: 3,
        row: 'E',
        number: 1,
    },
    {
        id: 334,
        screen_id: 3,
        row: 'E',
        number: 2,
    },
    {
        id: 335,
        screen_id: 3,
        row: 'E',
        number: 3,
    },
    {
        id: 336,
        screen_id: 3,
        row: 'E',
        number: 4,
    },
    {
        id: 337,
        screen_id: 3,
        row: 'E',
        number: 5,
    },
    {
        id: 338,
        screen_id: 3,
        row: 'E',
        number: 6,
    },
    {
        id: 339,
        screen_id: 3,
        row: 'E',
        number: 7,
    },
    {
        id: 340,
        screen_id: 3,
        row: 'E',
        number: 8,
    },
    {
        id: 341,
        screen_id: 3,
        row: 'E',
        number: 9,
    },
    {
        id: 342,
        screen_id: 3,
        row: 'E',
        number: 10,
    },
    {
        id: 343,
        screen_id: 3,
        row: 'F',
        number: 1,
    },
    {
        id: 344,
        screen_id: 3,
        row: 'F',
        number: 2,
    },
    {
        id: 345,
        screen_id: 3,
        row: 'F',
        number: 3,
    },
    {
        id: 346,
        screen_id: 3,
        row: 'F',
        number: 4,
    },
    {
        id: 347,
        screen_id: 3,
        row: 'F',
        number: 5,
    },
    {
        id: 348,
        screen_id: 3,
        row: 'F',
        number: 6,
    },
    {
        id: 349,
        screen_id: 3,
        row: 'F',
        number: 7,
    },
    {
        id: 350,
        screen_id: 3,
        row: 'F',
        number: 8,
    },
    {
        id: 351,
        screen_id: 3,
        row: 'F',
        number: 9,
    },
    {
        id: 352,
        screen_id: 3,
        row: 'F',
        number: 10,
    },
    {
        id: 353,
        screen_id: 3,
        row: 'G',
        number: 1,
    },
    {
        id: 354,
        screen_id: 3,
        row: 'G',
        number: 2,
    },
    {
        id: 355,
        screen_id: 3,
        row: 'G',
        number: 3,
    },
    {
        id: 356,
        screen_id: 3,
        row: 'G',
        number: 4,
    },
    {
        id: 357,
        screen_id: 3,
        row: 'G',
        number: 5,
    },
    {
        id: 358,
        screen_id: 3,
        row: 'G',
        number: 6,
    },
    {
        id: 359,
        screen_id: 3,
        row: 'G',
        number: 7,
    },
    {
        id: 360,
        screen_id: 3,
        row: 'G',
        number: 8,
    },
    {
        id: 361,
        screen_id: 3,
        row: 'G',
        number: 9,
    },
    {
        id: 362,
        screen_id: 3,
        row: 'G',
        number: 10,
    },
    {
        id: 363,
        screen_id: 3,
        row: 'G',
        number: 11,
    },
    {
        id: 364,
        screen_id: 3,
        row: 'H',
        number: 1,
    },
    {
        id: 365,
        screen_id: 3,
        row: 'H',
        number: 2,
    },
    {
        id: 366,
        screen_id: 3,
        row: 'H',
        number: 3,
    },
    {
        id: 367,
        screen_id: 3,
        row: 'H',
        number: 4,
    },
    {
        id: 368,
        screen_id: 3,
        row: 'H',
        number: 5,
    },
    {
        id: 369,
        screen_id: 3,
        row: 'H',
        number: 6,
    },
    {
        id: 413,
        screen_id: 3,
        row: 'D',
        number: 12,
    },
    {
        id: 414,
        screen_id: 3,
        row: 'D',
        number: 13,
    },
    {
        id: 415,
        screen_id: 3,
        row: 'D',
        number: 14,
    },
    {
        id: 452,
        screen_id: 3,
        row: 'F',
        number: 11,
    },
    {
        id: 453,
        screen_id: 3,
        row: 'E',
        number: 11,
    },
    {
        id: 454,
        screen_id: 3,
        row: 'E',
        number: 12,
    },
    {
        id: 455,
        screen_id: 3,
        row: 'E',
        number: 13,
    },
    {
        id: 456,
        screen_id: 3,
        row: 'E',
        number: 14,
    },
    {
        id: 466,
        screen_id: 3,
        row: 'B',
        number: 11,
    },
    {
        id: 467,
        screen_id: 3,
        row: 'B',
        number: 12,
    },
    {
        id: 468,
        screen_id: 3,
        row: 'B',
        number: 13,
    },
    {
        id: 479,
        screen_id: 3,
        row: 'C',
        number: 11,
    },
    {
        id: 480,
        screen_id: 3,
        row: 'C',
        number: 12,
    },
    {
        id: 481,
        screen_id: 3,
        row: 'C',
        number: 13,
    },
    {
        id: 482,
        screen_id: 3,
        row: 'B',
        number: 14,
    },
    {
        id: 483,
        screen_id: 3,
        row: 'C',
        number: 14,
    },
    {
        id: 484,
        screen_id: 3,
        row: 'A',
        number: 10,
    },
    {
        id: 485,
        screen_id: 3,
        row: 'A',
        number: 11,
    },
    {
        id: 486,
        screen_id: 3,
        row: 'A',
        number: 12,
    },
    {
        id: 487,
        screen_id: 3,
        row: 'A',
        number: 13,
    },
];

arr.sort((a, b) => {
    if (a.row < b.row) return -1;
    if (a.row > b.row) return 1;
    return a.number - b.number;
});
console.log(arr);
